# Generated by Django 5.1 on 2024-08-14 04:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('discription', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='Brands/% Y/% m/% d/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 14, 9, 37, 1, 587522))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('discription', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 14, 9, 37, 1, 587522))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secondry_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='Products/% Y/% m/% d/')),
                ('image_2', models.ImageField(upload_to='Products/% Y/% m/% d/')),
                ('image_3', models.ImageField(upload_to='Products/% Y/% m/% d/')),
                ('image_4', models.ImageField(upload_to='Products/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='Products/% Y/% m/% d/')),
                ('quantity', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_system', models.CharField(default='Android', max_length=25)),
                ('processor', models.CharField(max_length=60)),
                ('screen_size', models.CharField(max_length=60)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcuts', to='Product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcuts', to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Product.product')),
            ],
        ),
    ]
