# Generated by Django 5.1 on 2024-08-14 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_product_price_variants_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 12, 24, 12, 319824)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 12, 24, 12, 319824)),
        ),
    ]
