# Generated by Django 5.1 on 2024-08-14 13:35

import Product.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_rename_discription_brand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='secondry_images',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 5, 12, 123305)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to=Product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 5, 12, 123305)),
        ),
        migrations.CreateModel(
            name='SecondaryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Products/%Y/%m/%d/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to='Product.variants')),
            ],
        ),
        migrations.DeleteModel(
            name='Secondry_images',
        ),
    ]
