# Generated by Django 5.1 on 2024-08-14 14:02

import Product.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_variants_secondry_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 32, 9, 340343)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 32, 9, 341343)),
        ),
        migrations.AlterField(
            model_name='secondaryimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.models.upload_to_v),
        ),
    ]
