# Generated by Django 5.1 on 2024-08-14 14:05

import Product.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_brand_created_at_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 35, 42, 822705)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 19, 35, 42, 822705)),
        ),
        migrations.AlterField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.models.upload_to_v),
        ),
    ]
