# Generated by Django 5.1 on 2024-09-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0050_alter_brand_created_at_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 23, 3, 395839)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 23, 3, 395839)),
        ),
        migrations.AlterField(
            model_name='variants',
            name='color',
            field=models.CharField(max_length=25, verbose_name='color name'),
        ),
    ]
