# Generated by Django 5.1 on 2024-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_custom_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
