# Generated by Django 5.1 on 2024-08-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
