# Generated by Django 5.1 on 2024-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('house_name', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40)),
                ('road', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
