# Generated by Django 5.1 on 2024-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Region',
            field=models.CharField(default='India', max_length=40),
        ),
    ]
