# Generated by Django 5.1 on 2024-08-21 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_brand_created_at_alter_category_created_at'),
        ('Users', '0009_alter_address_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(default='India', max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('house_name', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40)),
                ('road', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyment_method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_daate', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.deliveryaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.variants')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.orders')),
            ],
        ),
    ]
