# Generated by Django 5.1 on 2024-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_deliveryaddress_orders_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_daate',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
