# Generated by Django 5.1 on 2024-08-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_rename_order_daate_orders_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
