# Generated by Django 5.1 on 2024-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_order_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
