# Generated by Django 5.1 on 2024-08-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_order_items_is_active_order_items_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
