# Generated by Django 5.1 on 2024-08-26 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 7, 12, 4, 174854, tzinfo=datetime.timezone.utc)),
        ),
    ]
