# Generated by Django 5.1 on 2024-08-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_wallet_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pyment_status',
            field=models.CharField(default='done', max_length=20),
            preserve_default=False,
        ),
    ]
