# Generated by Django 5.1 on 2024-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_orders_pyment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
