# Generated by Django 5.1 on 2024-08-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_remove_order_items_unit_price_cart_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='unit_price',
        ),
    ]
