# Generated by Django 5.1 on 2024-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
