# Generated by Django 5.1 on 2024-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_order_items_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(default='credit', max_length=50),
        ),
    ]
