# Generated by Django 5.1 on 2024-09-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.orders'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.order_items'),
        ),
    ]
