# Generated by Django 5.1 on 2024-09-04 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_alter_brand_created_at_alter_category_created_at'),
        ('Users', '0026_transactions_order_alter_transactions_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.variants'),
        ),
    ]
