# Generated by Django 5.1 on 2024-09-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_alter_transactions_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_charge',
            field=models.IntegerField(default=50),
        ),
    ]
