# Generated by Django 5.1 on 2024-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_orders_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
