# Generated by Django 5.1 on 2024-09-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0049_alter_brand_created_at_alter_category_created_at'),
        ('Users', '0029_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Product.variants'),
        ),
    ]
