# Generated by Django 5.1 on 2024-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_order_items_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
