# Generated by Django 5.1 on 2024-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_brand_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_offer',
            name='percentage',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='product_offer',
            name='percentage',
            field=models.CharField(max_length=3),
        ),
    ]
