# Generated by Django 5.1 on 2024-08-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_order_items_unit_price'),
        ('admin_panel', '0004_coupon_coupon_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_usage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.orders'),
        ),
    ]
