# Generated by Django 5.1 on 2024-08-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_order_items_unit_price'),
        ('admin_panel', '0006_alter_coupon_usage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_usage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='Users.orders'),
        ),
    ]
