# Generated by Django 5.1 on 2024-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_coupon_usage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=10.1, max_digits=10),
        ),
    ]
